### ISSUE TITLE
rationale for Analytics::new()

### ISSUE THREAD

**Issue by 8ctopus** [aawnu/php-ga4#32]
Hi again Alex,

What is the rationale for `Analytics::new('G-XXXXXX', 'eMVPMEcTbaI1iuWtrPw', true)` instead of `new Analytics('G-XXXXXX', 'eMVPMEcTbaI1iuWtrPw', true)`?

**Comment by aawnu** [comment]
> Hi again Alex,
> 
> What is the rationale for `Analytics::new('G-XXXXXX', 'eMVPMEcTbaI1iuWtrPw', true)` instead of `new Analytics('G-XXXXXX', 'eMVPMEcTbaI1iuWtrPw', true)`?

Thats mainly a readability thing for quick nested methods

```
$analytics = new Analytics('G-XXXXXX', 'eMVPMEcTbaI1iuWtrPw', true);
$analytics->mehod()
    ->method()
    ->method();
```
compared to
```
$analytics = (new Analytics('G-XXXXXX', 'eMVPMEcTbaI1iuWtrPw', true))
    ->mehod()
    ->method()
    ->method();
```
compared to
```
$analytics = Analytics::new('G-XXXXXX', 'eMVPMEcTbaI1iuWtrPw', true)
    ->mehod()
    ->method()
    ->method();
```

**Comment by 8ctopus** [comment]
Oh I see, thank you for the explanation, I mainly use the second option, now I know one more.
