### ISSUE TITLE
If you follow the code then you will see there is 3 layers.

### ISSUE THREAD

**Issue by srakl** [aawnu/php-ga4#57]
If you follow the code then you will see there is 3 layers.

Analytics[ Events[ Items ] ] ]

Add `src/Item.php` to your `src/Event/BeginCheckout.php` event, then add the event to `src/Analytics.php`.

> You should not be able to `addItem` on `Analytics`, if this is doable then I will fix it later.

_Originally posted by @aawnu in https://github.com/aawnu/php-ga4/issues/55#issuecomment-1606123770_

sorry i really dont understand what you mean.  how do i add items to my events?
            
in your begincheckout class you do have this

```
  public function addItem(Facade\Type\ItemType $item)
    {
        $this->items[] = $item->toArray();
        return $this;
    }
```

and i did add it.

```
$analytics->addItem([
                'item_id' => 'bla bla',
                'currency'=> 'USD',
                'price'   =>'60.00',
                'quantity'=> 1
            ]);
```

**Comment by aawnu** [comment]
Okay, you need to first populate an item, then you need to make your event and pass the item to that event, and finally add it to the Analytics call.

```php 
$item = AlexWestergaard\PhpGa4\Item::new() // This is a CLASS not an ARRAY
    ->setItemId('blabla')
    ->setCurrency('usd')
    ->setPrice(60)
    ->setQuantity(1);

$event = AlexWestergaard\PhpGa4\Event\BeginCheckout::new()
    ->{your params here}
    ->addItem($item); // <--- You need to add the item to the EVENT, not ANALYTICS

$anayltics = AlexWestergaard\PhpGa4\Analytics::new('id', 'secret')
    ->setClient('bla')
    ->addEvent($event); // You need to add the EVENT to ANAYLTICS, where in EVENT contains ITEMS

$analytics->post(); // This you want a try-catch around as is throws on errors, it returns void
```

You can NOT add Items to ANALYTICS and you can not pass ARRAY as argument as it is validated on `items->toArray()` that all REQUIRED parameters are set inside of `src/Helper/IOHelper.php`.
