### ISSUE TITLE
README _gid cookie question

### ISSUE THREAD

**Issue by 8ctopus** [aawnu/php-ga4#58]
I never get the `_gid` cookie, does it still exist? If not, we should remove it from the readme

```php
$session = $_COOKIE['_ga'] ?? $_COOKIE['_gid'] ?? $_COOKIE['PHPSESSID'];
```

**Comment by aawnu** [comment]
I just opened a random website with Analytics and it still sets tha `_gid` cookie in my browser. It is not officialy mentioned in the Google Cookie's list, but is should be a 24-hour representative cookie where the `_ga` cookie is a session representative. This way it notice if its a returning user; <as far as I understand the difference>.
