### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by ycrz** [aawnu/php-ga4#82]
Dear aaw,
i've been working on PHP GA4 but still failed to set logEvent on php
on react this worked

import { getAnalytics, logEvent } from "firebase/analytics";
const analytics = getAnalytics();
logEvent(analytics, 'whatever', { name: 1});

So how to set it by using your library?
Thank you. Regards

**Comment by aawnu** [comment]
Thank you for adding it here. As stated on in the email, I would like more information on how you communicate between react and the php library, or what exactly you are trying to accomplish.

I am not familiar with firebase/analytics library.

**Comment by ycrz** [comment]
hmm basically on the php, i want to send event just like this image bellow like i did on react native:
![image](https://github.com/aawnu/php-ga4/assets/29294468/535768d0-fbd3-458a-80d6-276a96a4a8ba)

**Comment by ycrz** [comment]
i want to achieve "custom event" on firebase

**Comment by aawnu** [comment]
> i want to achieve "custom event" on firebase

I do not know how to achieve this within the `firebase/analytics` library/module.

**Comment by ycrz** [comment]
so what i need to do is make a new class that contain my object? oke will check thanks

**Comment by aawnu** [comment]
I'm closing this issue due to 3 days of no further questions.
