### ISSUE TITLE
[Bug] When sending request without user_id

### ISSUE THREAD

**Issue by everully** [aawnu/php-ga4#93]
If I send post without and do not provide user_id the script fails with the error:

`Typed property AlexWestergaard\PhpGa4\Analytics::$user_id must not be accessed before initialization`

How to reproduce:

```php
$client->setClientId($data->client_id)
    ->setTimestampMicros($data->timestamp)
    ->addEvent($event)
    ->post();
```

Because property $user_id does not have a default value and is not set in the constructor.
But it works if add ->setUserId('') like:

```php
$client->setClientId($data->client_id)
    ->setTimestampMicros($data->timestamp)
    ->addEvent($event)
    ->setUserId('')
    ->post();
```

Environment: PHP 8.3.0

**Comment by aawnu** [comment]
Hello!

I will have look in a minute from pc.

**Comment by aawnu** [comment]
This should be fixed now:
https://github.com/aawnu/php-ga4/releases/tag/v1.2.3
